---
abstract: 'Perl driver for the Loupedeck CT keyboard'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Test::Deep: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HID-LoupedeckCT
no_index:
  directory:
    - t
    - inc
requires:
  Future::Mojo: '0'
  IO::Interface::Simple: '0'
  Imager: '0'
  Imager::File::PNG: '0'
  Mojolicious: '0'
  Moo: '2'
  perl: '5.020'
resources:
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/HID-LoupedeckCT.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
